name: Build and Update Github Pages

on: 
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1.2.0
        with:
          node-version: "10.x"

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          # set up private key for deploy
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # set git infomation
          git config --global user.name 'tevic'
          git config --global user.email 'tevic@users.noreply.github.com'
          # install dependencies
          npm install -g hexo-cli
          npm i

      - name: Deploy
        run: |
          hexo clean && hexo generate && hexo deploy
