name: Build and Update Github Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@gh-pages
    - name: Clean
      uses: heowc/action-hexo@master
      with:
        args: clean
    - name: Generate
      uses: heowc/action-hexo@master
      with:
        args: generate
    - name: Deploy
      uses: heowc/action-hexo@master
      env:
        EMAIL: tevic.tt@gmail.com
        NAME: tevic
      with:
        args: deploy